// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LoginSystem","status":true,"description":"Supabase authentication system with login, registration, and guest mode.","parameters":{"enableGuestMode":"true","sessionTimeout":"1440"}}
];
