// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LoginSystem","status":true,"description":"Supabase authentication system with login, registration, and guest mode.","parameters":{"enableGuestMode":"true","sessionTimeout":"1440"}},
{"name":"ChatDataManager","status":true,"description":"Chat data manager for Supabase integration","parameters":{}},
{"name":"Scene_Chat","status":true,"description":"Main chat scene","parameters":{}},
{"name":"Window_ChatMessage","status":true,"description":"Chat message display window","parameters":{}},
{"name":"Window_ChatInput","status":true,"description":"Chat input window","parameters":{}},
{"name":"ChatSystem","status":true,"description":"Global chat functionality with message posting and replies","parameters":{"enableChatMenu":"true","chatCommand":"Chat","maxMessagesPerPage":"50"}},
{"name":"renameoptions","status":true,"description":"","parameters":{}}
];
